language: scala

scala:
  - 2.11.12
  - 2.12.11
  - 2.13.1

before_install:
  - git fetch --tags

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    - script: sbt "++ ${TRAVIS_SCALA_VERSION}!" test
    - stage: release
      jdk: oraclejdk8
      script: sbt ci-release

jdk:
  - openjdk8
  - openjdk11
